import type { Lang } from '../app';

export const desktopCopy = {
  zh: {
    nav: { paper: '科研图', ppt: '幻灯片', templates: '模板库', history: '历史', workbench: '工作台', settings: '设置', about: '项目介绍' },
    simple: { label: '简单模式', hint: '不调用制图模型，只输出最终制图提示词；对之后提交的任务生效' },
    workbenchIntro: '框选修补错字、恢复可编辑文本、按原图像素裁剪，并以无损 PNG 导出。',
    settingsIntro: '配置 Design / Implement / Search 模型，以及代理与并发。',
    theme: { light: '切换到浅色模式', dark: '切换到深色模式' },
    about: {
      title: '项目介绍',
      intro: '了解 DreamPaper、项目地址与版本更新。',
      description: '本地科研配图与学术幻灯片，从模板到成图一步到位。',
      version: '当前版本',
      repository: '项目地址',
      openRepository: '打开 GitHub 项目',
      update: '版本更新',
      autoCheck: '启动时自动检查更新',
      autoCheckHint: '默认开启。关闭后启动时不联网，仍可随时手动检查。',
      check: '检查更新',
      checking: '检查中…',
      idle: '点击检查 GitHub 上的最新 Release。',
      latest: '已是最新版本',
      available: (version: string) => `发现新版本 v${version}`,
      failed: '检查更新失败',
      download: '下载更新',
      releases: '查看 Releases',
      openFailed: '无法打开外部链接'
    },
    tasks: { label: '任务页', add: '新建任务页', close: '关闭任务页', untitled: (n: number) => `任务 ${n}`, full: (max: number) => `最多同时打开 ${max} 个任务页` },
    recent: { title: '近期任务', empty: '还没有任务', failed: '失败', running: '进行中', done: '完成', untitled: '未命名任务', finishedAt: '完成于', delete: '删除', confirmDelete: '确认删除', deleteFailed: '删除任务失败', rerun: '重跑', rerunFailed: '重跑失败', rerunUnavailable: '该任务缺少原始输入，无法重跑' },
    history: {
      title: '历史记录',
      intro: '全部任务的完整档案：分页浏览，按类型、运行模式与状态筛选，按标题搜索。',
      all: '全部',
      filterMode: '按类型筛选',
      filterStatus: '按状态筛选',
      searchPlaceholder: '搜索标题…',
      emptyFiltered: '没有符合筛选条件的任务',
      prev: '上一页',
      next: '下一页',
      count: (n: number) => `共 ${n} 条`,
      today: '今天',
      yesterday: '昨天',
      earlier: '更早',
      stopped: '已停止',
      zoom: '放大图片',
      closePreview: '关闭预览',
      ratingTitle: '用户评分',
      rating: { good: '优', fair: '良', poor: '差' },
      simple: '简单模式',
      normal: '普通模式',
      simpleHint: '这次只产出制图提示词，没有成品图；预览显示的是所选母版。',
      reference: '预览：所选母版',
      filterSimple: '按运行模式筛选'
    },
    pane: {
      form: '参数',
      templates: '模板',
      master: '母版',
      result: '结果',
      material: '资料',
      resultEmpty: '提交任务后，这里显示进度与产出',
      selected: (n: number, max: number) => `已选 ${n}/${max}`,
      count: (n: number) => `${n} 张`,
      search: '搜索模板',
      masterNone: '尚未选择母版',
      removeFile: '移除',
      goTemplates: '前往模板库',
      figureEmpty: '模板库里还没有科研绘图模板',
      masterEmpty: '模板库里还没有幻灯片母版',
      emptyHint: '到模板库页导入后即可在这里选择。',
      rulesFold: '展开约束',
      rulesUnfold: '收起约束'
    },
    style: {
      font: '字体',
      fontNone: '默认字体',
      background: '背景色',
      hex: '#RRGGBB',
      palette: '常用背景色',
      eyedropper: '取色器',
      eyedropperHint: '取色器：在屏幕上点选颜色',
      systemPicker: '系统调色板',
      clear: '清除',
      invalidHex: '请输入 6 位十六进制颜色，如 #FFFFFF',
      fontLine: (font: string) => `全部文字统一使用字体「${font}」。`,
      backgroundLine: (hex: string) => `整体背景色使用 ${hex}。`
    },
    templates: {
      title: '模板库',
      intro: '科研图以模板作 few-shot 参考，幻灯片以母版定版式。两类分开管理，导入也在这里。',
      tabFigure: '科研绘图模板',
      tabMaster: '幻灯片母版',
      importImage: '导入图片',
      importPack: '导入模板包',
      importTitle: '导入',
      packHint: '选择解压后的 PaperBananaBench 目录（内含 diagram/ 与 plot/ 子目录及 ref.json）',
      pickPack: '选择目录…',
      kind: '类型',
      category: '分类',
      categoryHint: '可选，如 architecture / bar chart',
      visualIntent: '视觉意图',
      visualIntentHint: '可选，这张图想表达什么',
      contentSummary: '内容描述',
      contentSummaryHint: '可选，图里画了什么',
      file: '模板图片',
      choose: '选择图片',
      submit: '导入',
      importing: '导入中…',
      imported: '已导入',
      importedPack: (count: number) => `已导入 ${count} 张模板`,
      needFile: '请先选择图片',
      search: '搜索',
      all: '全部',
      diagram: '示意图',
      plot: '图表',
      master: '母版',
      count: (n: number) => `共 ${n} 张`,
      figureEmptyTitle: '还没有科研绘图模板',
      figureEmptyBody:
        '科研图模式需要参考图库。下载 PaperBananaBench 解压后，用「导入」里的模板包选择该目录；或先单张导入几张自有模板。',
      masterEmptyTitle: '还没有幻灯片母版',
      masterEmptyBody: '导入一张排版好的幻灯片截图作母版，幻灯片页就能直接选它定版式。',
      emptyLink: '下载 PaperBananaBench',
      select: '选择',
      selectDone: '退出选择',
      selectAll: '全选',
      selectNone: '取消全选',
      selectedCount: (n: number) => `已选 ${n} 张`,
      remove: '删除',
      confirmRemove: (n: number) => `确认删除 ${n} 张`,
      removing: '删除中…',
      removed: (n: number) => `已删除 ${n} 张模板`,
      removeNone: '请先选中要删除的模板'
    }
  },
  en: {
    nav: { paper: 'Figure', ppt: 'Slide', templates: 'Templates', history: 'History', workbench: 'Workbench', settings: 'Settings', about: 'About' },
    simple: { label: 'Simple mode', hint: 'Skip the drawing model and output the final drawing prompt only; applies to jobs submitted from now on' },
    workbenchIntro: 'Repair text, crop at source pixels, and export a lossless PNG.',
    settingsIntro: 'Configure Design / Implement / Search models, proxy and concurrency.',
    theme: { light: 'Switch to light mode', dark: 'Switch to dark mode' },
    about: {
      title: 'About',
      intro: 'Learn about DreamPaper, its repository, and available updates.',
      description: 'Local paper figures and academic slides — template in, publication-ready image out.',
      version: 'Current version',
      repository: 'Repository',
      openRepository: 'Open GitHub repository',
      update: 'Updates',
      autoCheck: 'Check for updates on startup',
      autoCheckHint: 'Enabled by default. Turn it off to skip network access at startup; manual checks remain available.',
      check: 'Check for updates',
      checking: 'Checking…',
      idle: 'Check the latest GitHub Release when you are ready.',
      latest: 'You are up to date',
      available: (version: string) => `Version v${version} is available`,
      failed: 'Update check failed',
      download: 'Download update',
      releases: 'View Releases',
      openFailed: 'Failed to open external link'
    },
    tasks: { label: 'Task tabs', add: 'New task tab', close: 'Close task tab', untitled: (n: number) => `Task ${n}`, full: (max: number) => `At most ${max} task tabs at once` },
    recent: { title: 'Recent jobs', empty: 'No jobs yet', failed: 'failed', running: 'running', done: 'done', untitled: 'Untitled task', finishedAt: 'finished at', delete: 'Delete', confirmDelete: 'Confirm', deleteFailed: 'Failed to delete job', rerun: 'Rerun', rerunFailed: 'Rerun failed', rerunUnavailable: 'Original input missing, cannot rerun' },
    history: {
      title: 'History',
      intro: 'The full archive of every job: paginated, filterable by kind, run mode and status, searchable by title.',
      all: 'All',
      filterMode: 'Filter by kind',
      filterStatus: 'Filter by status',
      searchPlaceholder: 'Search titles…',
      emptyFiltered: 'No jobs match the current filters',
      prev: 'Previous',
      next: 'Next',
      count: (n: number) => `${n} total`,
      today: 'Today',
      yesterday: 'Yesterday',
      earlier: 'Earlier',
      stopped: 'Stopped',
      zoom: 'Zoom image',
      closePreview: 'Close preview',
      ratingTitle: 'Your rating',
      rating: { good: 'Good', fair: 'Fair', poor: 'Poor' },
      simple: 'Simple',
      normal: 'Standard',
      simpleHint: 'This run only produced the drawing prompts — there is no finished image, so the preview shows the template you picked.',
      reference: 'Preview: the template you picked',
      filterSimple: 'Filter by run mode'
    },
    pane: {
      form: 'Parameters',
      templates: 'Templates',
      master: 'Master',
      result: 'Result',
      material: 'Material',
      resultEmpty: 'Progress and output appear here once a job is submitted',
      selected: (n: number, max: number) => `${n}/${max} selected`,
      count: (n: number) => `${n} items`,
      search: 'Search templates',
      masterNone: 'No master selected',
      removeFile: 'Remove',
      goTemplates: 'Open template library',
      figureEmpty: 'No figure templates in the library yet',
      masterEmpty: 'No slide masters in the library yet',
      emptyHint: 'Import them on the Templates page and they show up here.',
      rulesFold: 'Show rules',
      rulesUnfold: 'Hide rules'
    },
    style: {
      font: 'Font',
      fontNone: 'Default font',
      background: 'Background',
      hex: '#RRGGBB',
      palette: 'Common backgrounds',
      eyedropper: 'Eyedropper',
      eyedropperHint: 'Eyedropper: pick a colour from the screen',
      systemPicker: 'System colour picker',
      clear: 'Clear',
      invalidHex: 'Enter a 6-digit hex colour such as #FFFFFF',
      fontLine: (font: string) => `Use the font "${font}" for all text.`,
      backgroundLine: (hex: string) => `Use ${hex} as the overall background colour.`
    },
    templates: {
      title: 'Template library',
      intro:
        'Figures use templates as few-shot references; slides use masters for layout. Both kinds live here, and so does importing.',
      tabFigure: 'Figure templates',
      tabMaster: 'Slide masters',
      importImage: 'Import image',
      importPack: 'Import pack',
      importTitle: 'Import',
      packHint: 'Pick the extracted PaperBananaBench directory (containing diagram/ and plot/ with ref.json)',
      pickPack: 'Choose directory…',
      kind: 'Kind',
      category: 'Category',
      categoryHint: 'Optional, e.g. architecture / bar chart',
      visualIntent: 'Visual intent',
      visualIntentHint: 'Optional, what the figure conveys',
      contentSummary: 'Content summary',
      contentSummaryHint: 'Optional, what is drawn',
      file: 'Template image',
      choose: 'Choose image',
      submit: 'Import',
      importing: 'Importing…',
      imported: 'Imported',
      importedPack: (count: number) => `Imported ${count} templates`,
      needFile: 'Choose an image first',
      search: 'Search',
      all: 'All',
      diagram: 'Diagram',
      plot: 'Plot',
      master: 'Master',
      count: (n: number) => `${n} total`,
      figureEmptyTitle: 'No figure templates yet',
      figureEmptyBody:
        'Figure mode needs a reference library. Download and extract PaperBananaBench, then use the pack importer to select that directory — or import a few of your own templates individually.',
      masterEmptyTitle: 'No slide masters yet',
      masterEmptyBody:
        'Import a screenshot of a well-laid-out slide as a master, then pick it on the Slide page to fix the layout.',
      emptyLink: 'Download PaperBananaBench',
      select: 'Select',
      selectDone: 'Done',
      selectAll: 'Select all',
      selectNone: 'Clear',
      selectedCount: (n: number) => `${n} selected`,
      remove: 'Delete',
      confirmRemove: (n: number) => `Delete ${n}?`,
      removing: 'Deleting…',
      removed: (n: number) => `Deleted ${n} templates`,
      removeNone: 'Select templates to delete first'
    }
  }
} as const;

export type DesktopCopy = (typeof desktopCopy)[Lang];

export const PAPER_BANANA_BENCH_URL = 'https://huggingface.co/datasets/dwzhu/PaperBananaBench';
